apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applicationset
  namespace: argocd
spec:
  source:
    repoURL: git@github.com:evercast-chris/argocd-example-apps.git
    targetRevision: chore/overlays
    path: overlays-app