apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base-apps 

namespace: argocd

patchesStrategicMerge:
- parentapp.yaml
- applicationset.yaml 

patchesJson6902:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: ApplicationSet
      name: test-appset
    path: AppNamePatch.yaml

patchesJson6902:
  - target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: parent-app
    path: RootAppNamePatch.yaml


