apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applicationset
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: git@github.com:evercast-chris/argocd-example-apps.git
    targetRevision: master
    path: applicationsets
  destination:
    server: https://kubernetes.default.svc