apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: parent-app
  namespace: argocd
spec:
  source:
    repoURL: git@github.com:evercast-chris/argocd-example-apps.git
    targetRevision: master
    path: overlays-apps/overlays-root
